module.exports = {
    list1: [
        "a curvy",
        "a chunky",
        "a box shaped",
        "a minimalist",
        "an asymmetric",
        "a circular",
        "a cubic",
        "a lopsided",
        "an abnormally tall",
        "a low profile",
        "a $5",
        "a cheap",
        "an elegant",
        "a smart",
        "a huge",
        "a long and shallow",
    ], list2: [
        "shelving unit",
        "storage unit",
        "storage box",
        "storage chest",
        "office cabinet",
        "desk",
        "trolley",
        "bedside cabinet",
        "wardrobe",
        "dressing table",
        "bed",
        "chest of drawers",
        "side table",
        "coffee table",
        "dining table",
        "nest of three tables",
        "holder for tea-light candles",
        "pot plant holder",
        "lamp",
        "bookcase",
        "sofa",
        "mirror",
        "chair",
        "bathroom sink",
    ], list3: [
        "with portholes",
        "with holders for jam jars",
        "with a string of pegs for holding notes",
        "which doubles as a chalk board",
        "with a perspex window in it",
        "in a bright primary color",
        "in black",
        "in white",
        "in a wood effect finish",
        "with a glass top",
        "with sliding doors",
        "with built in coat hooks",
        "which doubles as a seat",
        "with fat tubular legs",
        "with thin metal legs",
        "supported by A-frames",
        "which can fold up when not in use",
        "which can stack one on top of the other",
        "which can hang on the wall when not in use",
    ]
}

